#!/bin/sh

if [ -z "$1" ]; then
    echo "Add message"
    exit 1
fi

zip -u submission.csv.zip submission.csv

kaggle competitions submit -c elo-merchant-category-recommendation -f submission.csv.zip  -m "$1"
